language: node_js
node_js: 6

install: "npm i"
script: "npm run test-with-coverage"

cache:
  directories:
    - node_modules

deploy:
  provider: npm
  email: "james@jamesswright.co.uk"
  api_key:
    secure: "IgDd7RMfLEysVzuJmPeHuiyg3V3nK9eb7rfdXdYbgSgkfFuUPck0VjUMB1vv9/7dnDolvEdJ3xGCuEbW2wX/5hq16x0k+WTfICrXy8uy2E8dhZsfYMeOqbvjNe/mahuJ4IfcM8gDptf8/oKGbUi2eeji2v1d726Hbd+R5cLu8vEVaJFxqH7io5HgZdwP2+n7r4CSpWjulz+XmamjKSH5FQ61GOBZNos/72Ef4T63KTbV9dYpIXpdACPryhv7U0BClxfIKewcFuaU707xbn5UanRpsD7nP5GMnhL+Jxu2UxVDiZ6oEvQbYLxen9gaKMbuvYd+xybztVIm4RRuxnZGBmJQ88o2CrXRSKdA368JFOwkZssmlXkTx5iutfP5qnT6MQ6WzX3z+o7sYLDEFwhV9aHwssfPhR/CKIMaRo2ZsSh+QsPUsedW8TNtpvxdhtecZv5JxwR8wQ9Ri/k5cTavvfwlhr0B+9e3H3E+tZ/V0KxloLLyL933z28RzAFywjwxuyhK/3BQuPdl2r5XD2EcqXHcuV4r/K0rPn033bqZ0vesqcI8NuYrfW//fr7WjT6Ugsd+G97TJwylOQduXJcbLTcChFwq7fyyxWUrV43ONCH5O5XRGcWiuwvLISwsOGuXwaMb+6jGcwm7KB3kyZaS2g3q4/5tK+TKGRVzjonMThA="

  on:
    tags: true
